name: CI - Validation
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main
env:
  pcfWorkkingDirectory: 'src/broadcast-pcf/appmodulepicker'
  broadcastjsWorkingDirectory: 'src/broadcast-typescript'
  solutionDirectory: 'src/broadcast-solution'
  artifactlocation: '${{ github.workspace }}/dist'
jobs:
    ValidationSolutionPack:
        if: ${{ github.event_name == 'pull_request'   }} 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Power Platform Tools
              uses: microsoft/powerplatform-actions/actions-install@v1
            - name: Pack solution
              uses: microsoft/powerplatform-actions/pack-solution@v1
              with:
                solution-folder: ${{ env.solutionDirectory}}
                solution-file: artifactlocation/broadcast_solution.zip
                solution-type: Unmanaged
    buildBroadCastJs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: ./github/workflows/templates/buildjs.yml
          with:
              projectdirectory: ${{ env.broadcastjsWorkingDirectory }}
              componentName: broadcastjs
              publishArtifact: false
              testCommand: 'test:ci'
              publishCodeCov: ${{github.event_name == 'pull_request'}}
              artifactlocation: ${{env.artifactlocation}}
          
  
            
    buildAppModulePickerPCF:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/workflows/templates/buildpcf.yml
              with:
                pcfdirectory: ${{ env.pcfWorkkingDirectory }}
                publishArtifact: false
                componentName: AppModulePicker