name: CI - Validation
permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main
env:
  pcfWorkkingDirectory: 'src/broadcast-pcf/appmodulepicker'
  broadcastjsWorkingDirectory: 'src/broadcast-typescript'
  solutionDirectory: 'src/broadcast-solution'
  artifactlocation: '${{ github.workspace }}/dist'
jobs:
    ValidationSolutionPack:
        if: ${{ github.event_name == 'pull_request'   }} 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Power Platform Tools
              uses: microsoft/powerplatform-actions/actions-install@v1
            - name: Pack solution
              uses: microsoft/powerplatform-actions/pack-solution@v1
              with:
                solution-folder: ${{ env.solutionDirectory}}
                solution-file: artifactlocation/broadcast_solution.zip
                solution-type: Unmanaged
    buildBroadCastJs:
        uses: ./.github/workflows/buildjs.yml
        with:
          projectdirectory: 'src/broadcast-typescript'
          componentName: broadcastjs
          publishArtifact: false
          testCommand: 'test:ci'
          publishCodeCov: true
          artifactlocation: '${{ github.workspace }}/dist'
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          
  
            
    buildAppModulePickerPCF:
        uses: ./.github/workflows/buildpcf.yml
        with:
          pcfdirectory: 'src/broadcast-pcf/appmodulepicker'
          publishArtifact: false
          componentName: AppModulePicker
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}