name: Create Release on Tag

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


env:
  pcfWorkkingDirectory: 'src/broadcast-pcf/appmodulepicker'
  broadcastjsWorkingDirectory: 'src/broadcast-typescript'
  solutionDirectory: 'src/broadcast-solution'
  artifactlocation: '${{ github.workspace }}/dist'
jobs:


 